module: OwnStonks
author: Kamaal Farah
github_url: https://github.com/kamaal111/OwnStonks
exclude:
  - Tests
copyright: "© 2021 Kamaal Farah under [open source license](https://github.com/kamaal111/OwnStonks/blob/main/LICENSE)."
output: JazzyDocs
