name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  XCODE_APP_NAME: Xcode_15.1.app

jobs:
  test-apple-platforms:
    name: Test Apple platforms
    timeout-minutes: 20
    runs-on: macos-13
    if: github.ref != 'refs/heads/main'
    strategy:
      matrix:
        test-commands: [
            "test-ios",
            # Can't use platform macOS yet, because macOS 14 is not supported yet on  GitHub actions
            # "test-macos"
          ]
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Install just
        uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Bootstrap project
        run: just bootstrap-apple-platforms

      - name: Test
        run: just "${{ matrix.test-commands }}"

      - name: Check diff
        run: just assert-has-no-diffs

  deploy-apple-platforms:
    name: Deploy Apple platforms
    timeout-minutes: 20
    runs-on: macos-13
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        deploy-commands: [
            "deploy-ios",
            # Can't use platform macOS yet, because macOS 14 is not supported yet on  GitHub actions
            # "deploy-macos"
          ]
    steps:
      - name: Checkout certificates
        uses: actions/checkout@v3
        with:
          repository: kamaal111/CodeSign
          ref: refs/heads/main
          token: ${{ secrets.CODE_SIGN_ACCESS_TOKEN }}

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Import signing private key
        env:
          SIGNING_PRIVATE_KEY: SigningCertificates/Distribution/Apple Distribution Kamaal Farah (DXUKH9VF73).p12
        run: just import-signing-private-key "${{ env.SIGNING_PRIVATE_KEY }}" "${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}" "${{ secrets.KEYCHAIN_PASSPHRASE }}"

      - name: Copy profiles
        run: just copy-profiles OwnStonks

      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Make env
        run: |
          rm -rf .env
          touch .env
          echo "GITHUB_TOKEN=\"${{ secrets.FEEDBACK_GITHUB_TOKEN }}\"" >> .env
          echo "FOREX_API_URL=\"${{ secrets.FOREX_API_URL }}\"" >> .env

      - name: Bootstrap project
        run: just bootstrap-apple-platforms

      - name: Bump version
        run: just bump-version ${{ github.run_number }}

      - name: Upload
        env:
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: just ${{ matrix.deploy-commands }}
